### ISSUE TITLE
Tentative Vision for the Game

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#1]
The game's mechanics will be split into two categories: The "main" game, and various "mini" games. The main game will provide an intuitive understanding of the concepts. The goal is that even if the player doesn't *try* to learn anything about genetics, just learning the mechanics will provide an intuitive understanding anyway. The mini games will be more technical conceptually, but easier to understand mechanically.

# Main game
## Storyline
An alien race is trying to invade Earth (or some other planet). To do this, they create cells/organisms designed to survive the harsh new environment. The player is responsible for giving the cells the correct traits to survive and ultimately become the dominant organism. I want to keep the story pretty basic, just enough setup to make sense. 

## Level plan
Each "world" consists of several levels.
### World 1: The ship 
The game begins on the alien spaceship. In the first few levels, the player will learn the very basics of the game's mechanics, the basics of what a trait is, and very simple inheritance. I'm envisioning the very first "level" teaching the player that putting eyes on a cell allows it to have a greater field of view, letting it see food. Toward's the end of the "world", the player should know what alleles are, what a Punnett square is (intuitively of course), and why traits are useful. We could probably show this with *just* the "eyes" trait.

### World 2, 3, 4, etc: The Planet
Each world after world 1 will be a different environment on the planet. The player will gradually unlock traits that provide specific benifits. The "fat" trait would be useful in an artic climate, while not as useful in an arid climate. Eyes might be useful in the daylight, but not in a cave environment. Specific levels should model scenarios that correspond to "real life facts", such as sickle cell anemia, Chernobyl, etc.

## Mechanics
This is somewhat TBD, but here is an initial effort. This is for Worlds 2 and beyond, but the initial world should sort of build to this point. I want to use the [cell stage](https://spore.fandom.com/wiki/Cell_Stage) of Spore as loose model of individual cell/organism interactions. Instead of controlling individual cells though, the gameplay will be more like [Bloons](https://ninjakiwi.com/Games/Mobile/Bloons-TD-6.html) or Plants vs Zombies. This means that the game will start out "paused", allowing the player to plan their strategy.  In the paused state, the camera will be focused on some number of "blank" cells. The player will drag and drop traits (individual alleles?) onto the cells. After they are done, they hit the "play" button, starting the level. During level progression, the cells have to deal with various hardships (starvation, predation, exposure, etc). If all of the cells die, then the player loses. The win condition is a little less clear, but it might be specific (need certain number of individuals with target trait, survived beyond the time limit, etc). The win condition might also be more broad, something like "become the dominant species". 

While the level is progressing, the player should have to do various things to better their chances of winning, without compromising the intuitive understanding of inheritance. This might be dragging traits onto cells, or maybe something equivalent to the bloons upgrade menu, but for traits. 
### The ecosystem system
There should be complex, autonomous interactions between both the player's cells, and the other organisms present in the level. The way that I came up with to model this, is with state machines (DFAs anyone?).  I already wrote the base code for this in my character.gd script, but essentially each organism in the level has a set of states and state transitions. While in a specific state, the cells will exhibit that behavior, then when a condition is met, they will move to another state. Each cell has its own state machine, controlled by the traits they have. This includes the "enemies" as well.

### The trait system
It's basically mendelian genetics (in the beginning). Each cell has a set of alleles and there is a dominant allele and a recessive allele. Based on the genotype, the cell will exhibit a phenotype. I think making the traits mostly dominant to start with would be more intuitive. As the game progresses, we should introduce traits that don't have the dominant/recessive expression, as well as more variants of the trait (blue eyes, green eyes, brown eyes). If we want to get really fancy, we could start to show multi-gene interactions as well, but that's a stretch goal for me.

I think it's a good idea to model the trait acquisitions on Plants vs Zombies. In that game, some plants are unlocked via the main story, but many are also unlocked through minigames, or by gaining enough currency (usually by playing minigames). We want to incentivize the player in a similar way, so that they play the mini games (most of the technical knowledge). 

During gameplay, the player starts out with an "allowance" of "trait points" that they can spend to put various traits on individual cells. These points also accumulate during the level based on some condition (reproductions? Rate of mutation? idk). The player can then choose to spend these points during the level to give more traits to their cells. I want there to be a reason for the player to stay invested in the gameplay while it is "playing".

# Mini games
Mini games should be simple, yet fun enough to be played multiple times. They should contain vocabulary terms that expand upon the gameplay mechanics in the main game. I think that minigames could be "triggered" during the main game as well as listed in a menu (these give currency to buy traits with). 

## Triggered minigames
I think it might be neat if these minigames had some effect on the outcome of the main game. They should be very simple and have some kind of time limit. 
### Mutation game (simple puzzle game)
Player is given a set of "mutations" and needs to transform one sequence of DNA into another. They use the mutations to manipulate the given DNA sequence into the target DNA sequence. There aren't that many types of simple mutations, so this would be great to show what each one does. 

Potentially, there could be a "mutation" event in the main game that generates a random new trait for that particular level. The player can choose to play this mini game to affect the outcome (good job = choose from small list of traits, bad job = random bad trait). There could be a time limit to increase tension.

### Protein folding game (simple puzzle game)
Player is shown a simple model of a protein, and has to manipulate it in some specific way to fold it into the correct shape. Maybe they are given a goal shape, maybe not. This should be a very simple game and could be triggered by the mutation event as well.

### punnett square game
Player can choose to fill out the punnett square of an organism mating to have some control over the offspring. This should only really be useful in the beginning of the game, and should become impossible as the number of traits increases. If the player doesn't click the punnett square popup in time, an animation will randomly choose the offspring (showing probability).

### More ideas
- Needs to teach/reinforce a concept
- Time limit
- Simple
## Non-triggered mini games
These could be longer, more complicated games that provide currency to buy traits with. They could even interrupt the level flow, as in plants vs zombies.

### Build the Codons (bullet hell)
This would play a lot like "dodge the creeps" I think. There are a bunch of DNA letters going across the screen and the player has to catch the ones that correspond to the amino acid they want. If they can build an entire protein, they win! 

The "player" in this case could be visually shown as a [tRNA](https://en.wikipedia.org/wiki/Transfer_RNA).
### More Ideas
- Engaging
- Can cover a complex topic
- Longer

**Comment by john-whiting** [comment]
I love the ideas! This will provide a pleasant experience for the players without getting too tedious. I will give the Punnett Square mini-game a go this weekend to get it into Godot.

**Comment by adediu25** [comment]
# Predator/Prey Tower Defense Minigame

## General Gameplay

Gameplay will be akin to a tower defense game, like Bloons Tower Defense. The player will play as the predators (the "towers"), and the enemies will be the prey. Predators placed near the paths of the prey will eat/kill prey that passes by. Predators and prey can have different traits/adaptations that affect interactions. Similar to how there are camo bloons in BTD that can only be detected by certain monkeys, we can have a camo adaptation for some of the prey, and they can only be detected if the predator has something like a "hunter eyesight" adaptation. 

Prey enters the screen in waves, which must be started by the player. Unlike Bloons, there is no direct penalty to letting prey exit the screen. The goal of the game is to reach the maximum score possible at the end of all the waves. This score can then be transferred to the main game. Although a player is not punished directly for letting prey free, it is in their best interest to make sure none escape to achieve a better score. Of course, score will increase with each prey captured, and that score can be used as a currency to add more predators or develop upgrades. Predator and adaptation descriptions can include relevant vocabulary and topics.

## More Specific Game Mechanics

- Two options for predators: 
  - All predators begin as a basic predator. Then, there can be upgrade paths or branches, such that choosing one upgrade blocks others from being chosen. We can develop these branches so that it makes sense from a biological standpoint
  - Different classes of predators, each with their own unique set of traits or abilities. Upgrades can be developed within that specific realm of traits.
- Trait interaction ideas
  - Night time mechanic where some waves are during the night, and only the predators that are nocturnal will be active
  - Maybe have some interaction between weight/size and speed. A larger predator could eat any prey that is smaller, but a drawback would be a decrease in speed which means they couldn't catch faster prey. Smaller predators can be faster but don't stand a chance against large prey
  - Pack mentality: certain predators can be more effective if multiple are placed in close proximity
  - We can have certain types of prey only appear once every 4 waves or so, and also have a mechanic where a predator will "die" if they do not eat for 3 full waves. This way, if a predator has been specialized to only eat that type of prey, it will not be able to survive. We can also extend this to teach overpopulation. If a player has too many predators, some of them may not manage to eat any prey, leading to starvation and death. 

These are some preliminary ideas for game mechanics to add to a simple tower defense style game. Feel free to drop any thoughts!

**Comment by IllustratedMan-code** [comment]
I wonder if you could integrate the idea of trophic Cascades somehow? Ie, if the predators eat *all* of the prey, then they don't have a food source and then they would die. Not exactly sure how to integrate into the tower defense idea though.

**Comment by IllustratedMan-code** [comment]
Move this to wiki
